# Generated by Django 5.1.7 on 2025-05-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], null=True),
        ),
    ]
